services:
  - type: web
    name: blu3-server
    env: node
    rootDir: blu3-server
    buildCommand: pip install yt-dlp && bun install --frozen-lockfile && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: CRYPTO_KEY
        sync: false
      - key: YT_COOKIES
        sync: false
      - key: YT_COOKIES_FILE
        value: ./cookies.json
    plan: standard
    autoDeploy: true
    healthCheckPath: /health
